cryptography/cryptography/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encryption_decryption/', include("encryption_decryption.urls"))
]

cryptography/encryption_decryption/urls.py
from django.urls import path 

from . import views

app_name="encryption_decryption"

urlpatterns = [
    path("",views.encryption, name="encrypt"),
    path("decrypt/", views.decryption, name="decrypt")
]

cryptography/encryption_decryption/models.py
from django.db import models

# Create your models here.

cryptography/encryption_decryption/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponse
from django.urls import reverse

from . import cryptography

class PasswordEncrypt(forms.Form):
    encrypt = forms.CharField(label="Enter your password to encrypt") 

class PasswordDecrypt(forms.Form):
    decrypt = forms.CharField(label="Enter your encrypted password to decrypt")

def encryption(request):
    if request.method == "POST":
        form = PasswordEncrypt(request.POST)
        if form.is_valid():
            encrypt = form.cleaned_data["encrypt"]
            request.session["encrypt"] = [encrypt]
            passwordMatrix=cryptography.PasswordMartix()
            encryptedPassword=passwordMatrix.encryption(encrypt)
            return HttpResponse(encryptedPassword)
        else:
            return render(request, "encryption_decryption/encrypt.html",{
                "form":form
            })

    return render(request, "encryption_decryption/encrypt.html",{
        "form":PasswordEncrypt
    })


def decryption(request):
    if request.method == "POST":
        form = PasswordDecrypt(request.POST)
        if form.is_valid():
            decrypt = form.cleaned_data["decrypt"]
            request.session["decrypt"] = [decrypt]
            passwordMatrix=cryptography.PasswordMartix()
            decryptedPassword=passwordMatrix.decryption(decrypt)
            return HttpResponse(decryptedPassword)
        else:
            return render(request, "encryption_decryption/decrypt.html",{
                "form":form
            })

    return render(request, "encryption_decryption/decrypt.html",{
        "form":PasswordDecrypt
    })

cryptography/encryption_decryption/templates/encryption_decryption/decrypt.html

{% extends "encryption_decryption/layout.html" %}
{% block body %}
    <h1> Add Tasks </h1>
    <form  action="{% url 'encryption_decryption:decrypt' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit"> 
    </form>
    <a href="{% url 'encryption_decryption:encrypt' %}">Encrypt Password</a>
{% endblock %}

cryptography/encryption_decryption/templates/encryption_decryption/encrypt.html

{% extends "encryption_decryption/layout.html" %}
{% block body %}
    <h1> Add Tasks </h1>
    <form  action="{% url 'encryption_decryption:encrypt' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit"> 
    </form>
    <a href="{% url 'encryption_decryption:decrypt' %}">Decrypt Password</a>
{% endblock %}

cryptography/encryption_decryption/templates/encryption_decryption/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Encrypt and Decrypt</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>